services:
  - type: web
    name: dr-will-downloader
    dockerfilePath: Dockerfile
    plan: free
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
